-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Client"
(
    "Id" uuid NOT NULL,
    "Phone" text COLLATE pg_catalog."default" NOT NULL,
    "FirstName" text COLLATE pg_catalog."default" NOT NULL,
    "Surname" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Client Id" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Inventory"
(
    "Id" uuid NOT NULL,
    "InventoryNumber" text COLLATE pg_catalog."default" NOT NULL,
    "IsAvailable" boolean,
    "InventoryModel" uuid NOT NULL,
    CONSTRAINT "Inventory Id" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."InventoryModel"
(
    "Id" uuid NOT NULL,
    "FullName" text COLLATE pg_catalog."default" NOT NULL,
    "InventoryType" uuid NOT NULL,
    CONSTRAINT "Inventory model Id" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Operator"
(
    "Id" uuid NOT NULL,
    "Phone" text COLLATE pg_catalog."default" NOT NULL,
    "PersonnelNumber" text COLLATE pg_catalog."default" NOT NULL,
    "FirstName" text COLLATE pg_catalog."default" NOT NULL,
    "Surname" text COLLATE pg_catalog."default" NOT NULL,
    "Patronymic" text COLLATE pg_catalog."default",
    CONSTRAINT "Operator Id" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Order"
(
    "Id" uuid NOT NULL,
    "Inventory" uuid NOT NULL,
    "Client" uuid NOT NULL,
    "Operator" uuid NOT NULL,
    "OrderDate" timestamp without time zone NOT NULL,
    "Comment" text COLLATE pg_catalog."default",
    CONSTRAINT "Order Id" PRIMARY KEY ("Id")
);

ALTER TABLE IF EXISTS public."Inventory"
    ADD CONSTRAINT "Model of inventory" FOREIGN KEY ("InventoryModel")
    REFERENCES public."InventoryModel" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Order"
    ADD CONSTRAINT "Order operator" FOREIGN KEY ("Operator")
    REFERENCES public."Operator" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Order"
    ADD CONSTRAINT "Ordered by" FOREIGN KEY ("Client")
    REFERENCES public."Client" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Order"
    ADD CONSTRAINT "Subject of order" FOREIGN KEY ("Inventory")
    REFERENCES public."Inventory" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;