-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."HubClient"
(
    "ClientHashKey" text COLLATE pg_catalog."default" NOT NULL,
    "LoadDate" timestamp without time zone NOT NULL,
    "RecordSource" text COLLATE pg_catalog."default" NOT NULL,
    "ClientNumber" text NOT NULL,
    CONSTRAINT "HubClient_pkey" PRIMARY KEY ("ClientHashKey")
);

CREATE TABLE IF NOT EXISTS public."HubInventory"
(
    "InventoryHashKey" text COLLATE pg_catalog."default" NOT NULL,
    "LoadDate" timestamp without time zone NOT NULL,
    "RecordSource" text COLLATE pg_catalog."default" NOT NULL,
    "InventoryNumber" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "HubInventory_pkey" PRIMARY KEY ("InventoryHashKey")
);

CREATE TABLE IF NOT EXISTS public."SatClient"
(
    "ClientHashKey" text NOT NULL,
    "Phone" text COLLATE pg_catalog."default" NOT NULL,
    "FirstName" text COLLATE pg_catalog."default" NOT NULL,
    "Surname" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Client Id" PRIMARY KEY ("ClientHashKey")
);

CREATE TABLE IF NOT EXISTS public."SatInventory"
(
    "InventoryHashKey" text NOT NULL,
    "InventoryNumber" text COLLATE pg_catalog."default" NOT NULL,
    "IsAvailable" boolean,
    "InventoryModel" uuid NOT NULL
);

CREATE TABLE IF NOT EXISTS public."SatInventoryModel"
(
    "InventoryModelHashKey" text NOT NULL,
    "FullName" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Inventory model Id" PRIMARY KEY ("InventoryModelHashKey")
);

CREATE TABLE IF NOT EXISTS public."SatOperator"
(
    "OperatorHashKey" text NOT NULL,
    "Phone" text COLLATE pg_catalog."default" NOT NULL,
    "PersonnelNumber" text COLLATE pg_catalog."default" NOT NULL,
    "FirstName" text COLLATE pg_catalog."default" NOT NULL,
    "Surname" text COLLATE pg_catalog."default" NOT NULL,
    "Patronymic" text COLLATE pg_catalog."default",
    CONSTRAINT "Operator Id" PRIMARY KEY ("OperatorHashKey")
);

CREATE TABLE IF NOT EXISTS public."LinkOrder"
(
    "OrderHashKey" text NOT NULL,
    "LoadDate" timestamp without time zone NOT NULL,
    "RecordSource" text NOT NULL,
    "Operator" text NOT NULL,
    "Client" text NOT NULL,
    "Inventory" text NOT NULL,
    CONSTRAINT "Order Id" PRIMARY KEY ("OrderHashKey")
);

CREATE TABLE IF NOT EXISTS public."HubInventoryModel"
(
    "InventoryModelHashKey" text NOT NULL,
    "LoadDate" timestamp without time zone NOT NULL,
    "RecordSource" text NOT NULL,
    PRIMARY KEY ("InventoryModelHashKey")
);

CREATE TABLE IF NOT EXISTS public."HubOperator"
(
    "OperatorHashKey" text NOT NULL,
    "LoadDate" timestamp without time zone NOT NULL,
    "RecordSource" text NOT NULL,
    PRIMARY KEY ("OperatorHashKey")
);

CREATE TABLE IF NOT EXISTS public."SatOrder"
(
    "OrderHashKey" text NOT NULL,
    "LoadDate" timestamp without time zone NOT NULL,
    "RecordSource" text NOT NULL,
    "OrderDate" timestamp without time zone NOT NULL,
    "Comment" text NOT NULL,
    PRIMARY KEY ("OrderHashKey")
);

CREATE TABLE IF NOT EXISTS public."LinkInventoryModel"
(
    "LinkInventoryModelHashKey" text NOT NULL,
    "InventoryModelHashKey" text NOT NULL,
    "InventoryHashKey" text NOT NULL,
    PRIMARY KEY ("LinkInventoryModelHashKey")
);

ALTER TABLE IF EXISTS public."SatClient"
    ADD FOREIGN KEY ("ClientHashKey")
    REFERENCES public."HubClient" ("ClientHashKey") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SatInventory"
    ADD FOREIGN KEY ("InventoryHashKey")
    REFERENCES public."HubInventory" ("InventoryHashKey") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SatInventoryModel"
    ADD FOREIGN KEY ("InventoryModelHashKey")
    REFERENCES public."HubInventoryModel" ("InventoryModelHashKey") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SatOperator"
    ADD FOREIGN KEY ("OperatorHashKey")
    REFERENCES public."HubOperator" ("OperatorHashKey") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."LinkOrder"
    ADD CONSTRAINT "Order operator" FOREIGN KEY ("Operator")
    REFERENCES public."HubOperator" ("OperatorHashKey") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."LinkOrder"
    ADD CONSTRAINT "Ordered by" FOREIGN KEY ("Client")
    REFERENCES public."HubClient" ("ClientHashKey") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."LinkOrder"
    ADD CONSTRAINT "Subject of order" FOREIGN KEY ("Inventory")
    REFERENCES public."HubInventory" ("InventoryHashKey") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."SatOrder"
    ADD FOREIGN KEY ("OrderHashKey")
    REFERENCES public."LinkOrder" ("OrderHashKey") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."LinkInventoryModel"
    ADD FOREIGN KEY ("InventoryModelHashKey")
    REFERENCES public."HubInventoryModel" ("InventoryModelHashKey") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."LinkInventoryModel"
    ADD FOREIGN KEY ("InventoryHashKey")
    REFERENCES public."HubInventory" ("InventoryHashKey") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
